vdus:
  vdu1:
    param:
      vm_image: cirros-0.3.4-x86_64-uec
      flavor: m1.tiny
      service: firewall
      pkt_in_network: net0
      pkt_out_network: net1
      zone: nova
      management: True
      network: net_mgmt
      mgmt_ip:
        - 192.168.120.98
      pkt_in_ip:
        - 10.10.0.98
      pkt_out_ip:
        - 10.10.1.98
